# Generated by Django 2.1.1 on 2018-10-15 15:20

import datetime
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.FileField(upload_to='', verbose_name='画像')),
            ],
        ),
        migrations.CreateModel(
            name='tabilog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('pub_date', models.DateTimeField(default=datetime.datetime.now)),
                ('author', models.CharField(max_length=100)),
                ('user_pk', models.IntegerField()),
                ('body', tinymce.models.HTMLField(verbose_name='content')),
                ('script', models.TextField(verbose_name='content')),
                ('is_editing', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='images',
            name='target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tabilog.tabilog', verbose_name='Link to an article'),
        ),
    ]
