# Generated by Django 2.1.1 on 2018-11-24 14:37

import datetime
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tabilog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('pub_date', models.DateTimeField(default=datetime.datetime.now)),
                ('author', models.CharField(max_length=30)),
                ('user_pk', models.IntegerField()),
                ('tag', models.CharField(max_length=100)),
                ('thumbnail', models.ImageField(blank=True, upload_to='thambnail/')),
                ('body', tinymce.models.HTMLField(verbose_name='body')),
                ('content', tinymce.models.HTMLField(verbose_name='content')),
                ('index', tinymce.models.HTMLField(blank=True, verbose_name='index')),
            ],
        ),
    ]
