# Generated by Django 2.1.1 on 2018-11-13 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tabilog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tabilog',
            old_name='thambnail',
            new_name='thumbnail',
        ),
    ]
